### ISSUE TITLE
Error in running the gmxvg

### ISSUE THREAD

**Issue by Khaten** [TheBiomics/GMXvg#10]
Dear Sir, I have successfully installed the gmxvg but while running the code - gmxvg --version, it states as this - 

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/home/khaten/anaconda3/envs/gmxMMPBSA/bin/gmxvg", line 8, in <module>
    sys.exit(xvgplot_cli())
  File "/home/khaten/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/gmxvg/__init__.py", line 5, in xvgplot_cli
    _m = GMXvg()
  File "/home/khaten/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/gmxvg/GMXvg.py", line 15, in __init__
    self.preset('data plot')
  File "/home/khaten/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/UtilityLib/utility.py", line 33, in preset
    _res.append(self.require('seaborn', "SNS"))
  File "/home/khaten/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/UtilityLib/core/base.py", line 228, in _import_single_module
    __i = MODULE_IMPORTER.import_module(_module)
  File "/home/khaten/anaconda3/envs/gmxMMPBSA/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/khaten/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/seaborn/__init__.py", line 2, in <module>
    from .rcmod import *  # noqa: F401,F403
  File "/home/khaten/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/seaborn/rcmod.py", line 5, in <module>
    import matplotlib as mpl
  File "/home/khaten/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/matplotlib/__init__.py", line 109, in <module>
    from . import _api, _version, cbook, docstring, rcsetup
  File "/home/khaten/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/matplotlib/rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/home/khaten/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/matplotlib/colors.py", line 56, in <module>
    from matplotlib import _api, cbook, scale
  File "/home/khaten/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/matplotlib/scale.py", line 23, in <module>
    from matplotlib.ticker import (
  File "/home/khaten/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/matplotlib/ticker.py", line 136, in <module>
    from matplotlib import transforms as mtransforms
  File "/home/khaten/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/matplotlib/transforms.py", line 46, in <module>
    from matplotlib._path import (
AttributeError: _ARRAY_API not found
Traceback (most recent call last):
  File "/home/khaten/anaconda3/envs/gmxMMPBSA/bin/gmxvg", line 8, in <module>
    sys.exit(xvgplot_cli())
  File "/home/khaten/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/gmxvg/__init__.py", line 5, in xvgplot_cli
    _m = GMXvg()
  File "/home/khaten/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/gmxvg/GMXvg.py", line 15, in __init__
    self.preset('data plot')
  File "/home/khaten/anaconda3/envs/gmxMMPBSA/lib/python3.9/site-packages/UtilityLib/utility.py", line 35, in preset
    self.PLOT.rcParams.update({'font.size': 24, 'font.family': 'Times New Roman'})
AttributeError: 'GMXvg' object has no attribute 'PLOT'

I would be glad if this issue can be resolved. Thank you.

**Comment by TheBiomics** [comment]
We have updated and release version 1.0.2. Expecting to fix these issues. And it is tested on MacOS (Mac Mini M4 and Windows in 3.12 python version). We will keep updating and rectifying issues.
